### PR TITLE
Wip/12/workplace ui

### PR DESCRIPTION
**Pull request by slytherin20**
Hi @Aniket762,
I have updated the UI of the workplace, please review it.
Before - 
Workplaces-before

After-
workplaces-after(1)

I have also fixed the header as you can see in both pictures and have done responsive styling as well.

### CODE REVIEW

**Comment by Aniket762** [comment]
Hey @slytherin20 I like the blue based theme mode it goes with the logo 

It will be great if you trying something else

**Comment by slytherin20** [comment]
Sure @Aniket762 I'll use blue color pallete then.

**Comment by slytherin20** [comment]
Please take a look at this one-
bluecolorpage

**Comment by slytherin20** [comment]
Let me know if it is satisfactory.

**Comment by slytherin20** [comment]
Hi @sayna3311 and @uditanshu23,
I have not received the feedback for the UI of the workplaces page. Please let me know if it is okay.

**Comment by uditanshu23** [comment]
Hi @slytherin20 !! Sorry for the late review. We have seen your work and are quite pleased with it and we are merging the request. Thank you for you work and happy coding! Cheers✌

**Pull request merged**
