### PR TITLE
Redesign Home Page

### PR DESCRIPTION
**Pull request by dfoltynski**
My screenshot button doesnt work 😅

### CODE REVIEW

**Comment by sumana2001** [comment]
Hey @dfoltynski 
If you're not able to take the screenshot a simple picture clicked from your mobile will also work.
Or you could list down the changes made.

**Comment by sumana2001** [comment]
Hey @dfoltynski
If you're not able to take the screenshot a simple picture clicked from your mobile will also work.
Or you could list down the changes made. 
Please try to reply asap as this is urgent

**Comment by dfoltynski** [comment]
image
image

**Review by abhibhaw — CHANGES_REQUESTED** [review]
Hello @dfoltynski, Kindly go through the following changes before this PR gets merged:

- [ ] Please Don't change the layout part (like shifting social links in the footer & Logo in the About Section).

- [ ] Compiling CSS files into one will be better.

- [ ] While Making any UI changes please attach the before and after ScreenShots side by side.

**Comment by abhibhaw** [comment]
Hey @dfoltynski, Are you still up for the changes?

**Pull request closed without merging**
